# Generated by Django 5.0.2 on 2024-02-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccounts_buy_history_delete_userprofile'),
        ('book_post', '0008_buynow_delete_borrowingtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='buy_history',
            field=models.ManyToManyField(to='book_post.buynow'),
        ),
        migrations.DeleteModel(
            name='BuyNow',
        ),
    ]
