# Generated by Django 5.0.2 on 2024-02-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_buynow_alter_userprofile_buy_history'),
        ('book_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cars',
            new_name='books',
        ),
        migrations.DeleteModel(
            name='BuyNow',
        ),
    ]
