# Generated by Django 5.0.2 on 2024-02-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_post', '0002_rename_cars_comment_books_delete_buynow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookposts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads/'),
        ),
    ]
