# Generated by Django 5.0.2 on 2024-02-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_post', '0003_alter_bookposts_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
