# Generated by Django 5.0.2 on 2024-02-24 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccounts_buy_history_delete_userprofile'),
        ('book_post', '0006_alter_bookposts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_post.bookposts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccounts')),
            ],
        ),
    ]
