# Generated by Django 5.0.2 on 2024-02-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_post', '0008_buynow_delete_borrowingtransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buynow',
            old_name='car',
            new_name='book',
        ),
    ]
